### ISSUE TITLE
Assertion failure on startup with musl libc

### ISSUE THREAD

**Issue by akdjka** [orbitalquark/textadept#297]
I wanted to try textadept_11.4 on my gentoo, but it dies immediately.
gdb tells me:
```➜  src git:(textadept_11.4)
➜  textadept git:(textadept_11.4) gdb ./textadept
GNU gdb (Gentoo 11.2 vanilla) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-gentoo-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./textadept...
(gdb) r
Starting program: /home/m/w/textadept/textadept
[New LWP 14619]
[New LWP 14620]
[New LWP 14686]
[LWP 14686 exited]
[New LWP 14688]
[New LWP 14689]
[LWP 14689 exited]
[New LWP 14691]
[LWP 14688 exited]
[New LWP 14693]
[LWP 14693 exited]
[LWP 14691 exited]
[New LWP 14694]
[New LWP 14711]
[LWP 14711 exited]
[New LWP 14714]
[New LWP 14715]
[New LWP 14716]
[LWP 14716 exited]
[LWP 14715 exited]
[LWP 14714 exited]
Assertion failed: (((((t))->tt_) == (((((5) | ((0) << 4))) | (1 << 6))))) && "table expected" (lua/src/lapi.c: gettable: 731)

Thread 1 "textadept" received signal SIGABRT, Aborted.
0x00007ffff7fd9b07 in setjmp () from /lib/ld-musl-x86_64.so.1
(gdb) bt
#0  0x00007ffff7fd9b07 in setjmp () at /lib/ld-musl-x86_64.so.1
#1  0x00007ffff7fd9c94 in raise () at /lib/ld-musl-x86_64.so.1
#2  0x0000003000000010 in  ()
#3  0x0000000000000000 in  ()
(gdb)
```

**Comment by orbitalquark** [comment]
Can you compile Textadept with debug symbols and try again? I cannot tell where it's failing from Textadept's perspective.

**Comment by akdjka** [comment]
This is with debug symbols. Without I don't even see assertion failure but a crash...
I tried strace to get a better understanding. And got:
```
(...)
munmap(0x7fcb38b5a000, 4096)            = 0
read(10, "^-1 * R('07'))^1 * -M.xdigit end"..., 1024) = 1024
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcb38b5a000
read(10, "al,\n-- octal, or binary number, "..., 1024) = 1024
read(10, "o_eol(prefix, escape)\n  return ("..., 1024) = 1024
read(10, "Optional flag indicating whether"..., 1024) = 1024
read(10, " identical, single-character str"..., 1024) = 1024
read(10, "(set) do set_chars[byte] = true "..., 1024) = 1024
read(10, ".colors = {} -- legacy\nM.styles "..., 1024) = 1024
read(10, "[{') * lexer.range('/')\n-- @name"..., 1024) = 1024
read(10, "class table\n-- @name line_state\n"..., 1024) = 668
readv(10, [{iov_base="", iov_len=356}, {iov_base="", iov_len=1024}], 2) = 0
munmap(0x7fcb393ee000, 16384)           = 0
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcb393ee000
close(10)                               = 0
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcb38ab3000
munmap(0x7fcb38ab7000, 28672)           = 0
munmap(0x7fcb38abe000, 32768)           = 0
madvise(0x7fcb38acf000, 4096, MADV_FREE) = 0
madvise(0x7fcb38b57000, 4096, MADV_FREE) = 0
munmap(0x7fcb38b3a000, 8192)            = 0
munmap(0x7fcb38b3c000, 8192)            = 0
munmap(0x7fcb38b5b000, 8192)            = 0
madvise(0x7fcb38b28000, 4096, MADV_FREE) = 0
madvise(0x7fcb38ecf000, 4096, MADV_FREE) = 0
madvise(0x7fcb38b03000, 8192, MADV_FREE) = 0
madvise(0x7fcb38b65000, 8192, MADV_FREE) = 0
madvise(0x7fcb38b62000, 8192, MADV_FREE) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcb38b5b000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcb38b3c000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcb38b3a000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcb38b26000
open("/text.lua", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)
open("/text.lua", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)
writev(2, [{iov_base="Assertion failed: ", iov_len=18}, {iov_base="(((((t))->tt_) == (((((5) | ((0)"..., iov_len=75}], 2Assertion failed: (((((t))->tt_) == (((((5) | ((0) << 4))) | (1 << 6))))) && "table expected") = 93
writev(2, [{iov_base=" (lua/src/lapi.c: gettable: 731)"..., iov_len=33}, {iov_base=NULL, iov_len=0}], 2 (lua/src/lapi.c: gettable: 731)
) = 33
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1 RT_2], [], 8) = 0
tkill(9285, SIGABRT)                    = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=9285, si_uid=1000} ---
+++ killed by SIGABRT +++
[1]    9282 abort      strace ./textadept
```
Is it looking for text.lua in the root of the filesystem?

**Comment by akdjka** [comment]
After some gdb tracing I got:
```
Thread 1 "textadept" hit Breakpoint 3, 0x00007ffff7fd9c50 in raise () from /lib/ld-musl-x86_64.so.1
(gdb) bt
#0  0x00007ffff7fd9c50 in raise () at /lib/ld-musl-x86_64.so.1
#1  0x00007ffff7f9e8ae in abort () at /lib/ld-musl-x86_64.so.1
#2  0x0000003300000000 in  ()
#3  0x0000000000000007 in  ()
#4  0xfffffffef5b4d97e in  ()
#5  0x00007ffff64f3678 in  ()
#6  0x00007ffff6475e28 in  ()
#7  0x00007ffff642ce20 in  ()
#8  0x00007fffffffba20 in  ()
#9  0x00007ffff7f9e967 in  () at /lib/ld-musl-x86_64.so.1
#10 0x00005555558d4698 in  ()
#11 0x000055555584643d in gettable (L=0x7ffff64f3678, idx=-2) at lua/src/lapi.c:731
#12 0x00005555558464ad in lua_rawget (L=0x7ffff64f3678, idx=-2) at lua/src/lapi.c:741
#13 0x00005555558906ff in LexerLPeg::PropertySet(char const*, char const*) (this=0x7ffff61da4e0, key=0x7ffff5b4d978 "style.default", value=0x7ffff5b3e7c8 "back:15132390,fore:3355443,font:Bitstream Vera Sans Mono,size:10")
    at LexLPeg.cxx:818
#14 0x0000555555822ef7 in Scintilla::Internal::LexState::PropSet(char const*, char const*) (this=
    0x7ffff62f4d20, key=0x7ffff5b4d978 "style.default", val=0x7ffff5b3e7c8 "back:15132390,fore:3355443,font:Bitstream Vera Sans Mono,size:10") at scintilla/src/ScintillaBase.cxx:661
#15 0x0000555555823f2a in Scintilla::Internal::ScintillaBase::WndProc(Scintilla::Message, unsigned long, long) (this=0x7ffff5fad050, iMessage=Scintilla::Message::SetProperty, wParam=140737315658104, lParam=140737315596232)
    at scintilla/src/ScintillaBase.cxx:1036
#16 0x00005555558a3ed5 in Scintilla::Internal::ScintillaGTK::WndProc(Scintilla::Message, unsigned long, long) (this=0x7ffff5fad050, iMessage=Scintilla::Message::SetProperty, wParam=140737315658104, lParam=140737315596232)
    at scintilla/gtk/ScintillaGTK.cxx:939
#17 0x00005555558ab364 in scintilla_send_message(ScintillaObject*, unsigned int, uptr_t, sptr_t) (sci=0x7ffff5fd2160, iMessage=4004, wParam=140737315658104, lParam=140737315596232) at scintilla/gtk/ScintillaGTK.cxx:3133
#18 0x00005555558b65a2 in call_scintilla (L=0x7ffff64f3678, view=0x7ffff5fd2160, msg=4004, wtype=7, ltype=7, rtype=0, arg=4) at textadept.c:1192
#19 0x00005555558b6b8b in property_newindex (L=0x7ffff64f3678) at textadept.c:1267
#20 0x00005555558568fb in precallC (L=0x7ffff64f3678, func=0x7ffff62026a0, nresults=0, f=0x5555558b6a57 <property_newindex>) at lua/src/ldo.c:506
#21 0x0000555555856c6c in luaD_precall (L=0x7ffff64f3678, func=0x7ffff62026a0, nresults=0) at lua/src/ldo.c:572
#22 0x0000555555856e4b in ccall (L=0x7ffff64f3678, func=0x7ffff62026a0, nResults=0, inc=1) at lua/src/ldo.c:607
#23 0x0000555555856ebc in luaD_call (L=0x7ffff64f3678, func=0x7ffff62026a0, nResults=0) at lua/src/ldo.c:619
#24 0x000055555587465a in luaT_callTM (L=0x7ffff64f3678, f=0x7ffff5b54d48, p1=0x7ffff6202660, p2=0x7ffff5ba5c00, p3=0x7ffff5ba5c10) at lua/src/ltm.c:113
#25 0x0000555555877621 in luaV_finishset (L=0x7ffff64f3678, t=0x7ffff6202660, key=0x7ffff5ba5c00, val=0x7ffff5ba5c10, slot=0x5555558d8340) at lua/src/lvm.c:354
#26 0x000055555587b064 in luaV_execute (L=0x7ffff64f3678, ci=0x7ffff642aeb0) at lua/src/lvm.c:1336
#27 0x0000555555856e73 in ccall (L=0x7ffff64f3678, func=0x7ffff5ba4a50, nResults=-1, inc=65537) at lua/src/ldo.c:609
#28 0x0000555555856eea in luaD_callnoyield (L=0x7ffff64f3678, func=0x7ffff5ba4a50, nResults=-1) at lua/src/ldo.c:627
#29 0x0000555555847890 in f_call (L=0x7ffff64f3678, ud=0x7fffffffcb20) at lua/src/lapi.c:1041
#30 0x0000555555855907 in luaD_rawrunprotected (L=0x7ffff64f3678, f=0x55555584785b <f_call>, ud=0x7fffffffcb20) at lua/src/ldo.c:144
#31 0x00005555558579c7 in luaD_pcall (L=0x7ffff64f3678, func=0x55555584785b <f_call>, u=0x7fffffffcb20, old_top=176, ef=0) at lua/src/ldo.c:926
#32 0x0000555555847ace in lua_pcallk (L=0x7ffff64f3678, nargs=0, nresults=-1, errfunc=0, ctx=0, k=0x55555584d31e <finishpcall>) at lua/src/lapi.c:1067
#33 0x000055555584d409 in luaB_pcall (L=0x7ffff64f3678) at lua/src/lbaselib.c:477
#34 0x00005555558568fb in precallC (L=0x7ffff64f3678, func=0x7ffff5ba4a30, nresults=2, f=0x55555584d393 <luaB_pcall>) at lua/src/ldo.c:506
#35 0x0000555555856c6c in luaD_precall (L=0x7ffff64f3678, func=0x7ffff5ba4a30, nresults=2) at lua/src/ldo.c:572
#36 0x0000555555880dfd in luaV_execute (L=0x7ffff64f3678, ci=0x7ffff6489df0) at lua/src/lvm.c:1636
#37 0x0000555555856e73 in ccall (L=0x7ffff64f3678, func=0x7ffff5ba49c0, nResults=1, inc=65537) at lua/src/ldo.c:609
#38 0x0000555555856eea in luaD_callnoyield (L=0x7ffff64f3678, func=0x7ffff5ba49c0, nResults=1) at lua/src/ldo.c:627
#39 0x0000555555847890 in f_call (L=0x7ffff64f3678, ud=0x7fffffffd850) at lua/src/lapi.c:1041
#40 0x0000555555855907 in luaD_rawrunprotected (L=0x7ffff64f3678, f=0x55555584785b <f_call>, ud=0x7fffffffd850) at lua/src/ldo.c:144
#41 0x00005555558579c7 in luaD_pcall (L=0x7ffff64f3678, func=0x55555584785b <f_call>, u=0x7fffffffd850, old_top=32, ef=0) at lua/src/ldo.c:926
#42 0x0000555555847ace in lua_pcallk (L=0x7ffff64f3678, nargs=1, nresults=1, errfunc=0, ctx=0, k=0x0) at lua/src/lapi.c:1067
#43 0x00005555558b29ca in emit (L=0x7ffff64f3678, name=0x5555558dbea4 "buffer_new") at textadept.c:233
#44 0x00005555558bc358 in main (argc=1, argv=0x7fffffffda28) at textadept.c:2554
```

**Comment by orbitalquark** [comment]
Thanks for the additional details. It appears to be an issue with lexer setup, but I cannot tell at first glance what is going wrong. I'll have to investigate when I have some time.

**Comment by orbitalquark** [comment]
With the first alpha of Textadept 12 right around the corner, the code at the source of the crash no longer exists (the C++ lexer has been completely rewritten), so this particular crash will no longer be an issue. Unfortunately, I will not be spending more time debugging this.

**Comment by akdjka** [comment]
I did a quick test and I see that textadept appears to be running on musl.
