### ISSUE TITLE
Segfault on FreeBSD

### ISSUE THREAD

**Issue by hellium6** [orbitalquark/textadept#478]
While trying to build Textadept 12.1 release on `FreeBSD 12.4-RELEASE i386` with:

```sh
## added ` iconv` in the `set(ta_link_libs...` line on root CMakeLists.txt as described in issue #477
$ cmake -S . -B build_dir -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=build_dir/install -D CMAKE_C_COMPILER=gcc13 -D CMAKE_CXX_COMPILER=g++13 -D CMAKE_EXE_LINKER_FLAGS="-rpath=/usr/local/lib/gcc13"  # rpath is from gcc13 install message
$ cmake --build build_dir -j
$ cmake --install build_dir
```

Running gives me a segfault:

```sh
$ build_dir/install/bin/textadept-gtk
Segmentation fault
```

`strace` shows:

```sh
$ strace build_dir/install/bin/textadept-gtk
strace: open("/proc/...", ...): No such file or directory
trouble opening proc file
```

`gdb` shows:

```
$ sudo gdb build_dir/install/bin/textadept-gtk
GNU gdb (GDB) 13.2 [GDB v13.2 for FreeBSD]
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "i386-portbld-freebsd12.4".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from build_dir/install/bin/textadept-gtk...
(gdb) run
Starting program: /usr/home/user/Downloads/textadept-textadept_12.1/build_dir/install/bin/textadept-gtk 
warning: File "/usr/local/lib/gcc13/libstdc++.so.6.0.31-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/local/lib/gcc13/libstdc++.so.6.0.31-gdb.py
line to your configuration file "/root/.config/gdb/gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/root/.config/gdb/gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
[New LWP 101097 of process 50902]
[New LWP 101288 of process 50902]

Thread 1 received signal SIGSEGV, Segmentation fault.
Address not mapped to object.
0x29745cc0 in strcmp () from /lib/libc.so.7
(gdb) backtrace
#0  0x29745cc0 in strcmp () at /lib/libc.so.7
#1  0x080b6c2e in luaS_new ()
#2  0x0809bfd1 in lua_setglobal ()
#3  0x0809380c in init_lua ()
#4  0x08096541 in init_textadept ()
#5  0x0808f0c6 in main ()
```

**Comment by orbitalquark** [comment]
Sorry, BSD is not supported. I don't have access to a BSD machine and haven't had any help in getting Textadept to work on it. Your crash is related to Textadept attempting to locate where it is. This might help: https://github.com/orbitalquark/textadept/commit/bb14dfe31c87ebf9b1489186c7a023ef6582d952#diff-e137203d90aa39a746e4bae862aff9bcd13a78d4f4fe2896b0046aba666f9ed5

**Comment by quesada** [comment]
FWIW, I use it on freeBSD too

**Comment by paaguti** [comment]
I've started a discussion, because I'm also interested in getting it compiled and running. ;-)
I've gone for the QT version, because I wanted to try KDE/plasma (5)

**Comment by orbitalquark** [comment]
Closing this in favor of the discussion here: https://github.com/orbitalquark/textadept/discussions/562

Textadept currently does not support BSD and I do not have the means to work on this at the moment.
